[package]
name = "yip"
version = "0.1.0"
authors = ["Kevin Gimbel <hallo@kevingimbel.com>"]
description = "TCP server that responds with callers IP address"
edition = "2018"
keywords = ["tcp", "server", "ip"]
[dependencies]
